import { useEffect, useState } from "react";
import { Col, Typography } from "antd";

import Head from "next/head";
import Image from "next/image";

import MainLayout from "../Components/MainLayout";
import Section from "../Components/Home/Section";

import Lamu2 from "../public/Lamu2.jpg";

import styles from "../styles/Home.module.css";

const { Title } = Typography;

const Home = () => {
  const [isShown, setIsShown] = useState(false);
  useEffect(() => {
    setIsShown(true);
  }, []);

  if (!isShown) {
    return null;
  }
  return (
    <MainLayout>
      <Head>
        <title>Travel Lamu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <Col span={24} className={styles.image} style={{ zIndex: 1 }}>
          <Image priority layout="fill" src={Lamu2} />
          <Title className={styles.title} level={4}>
            Travel Lamu
          </Title>
        </Col>
      </Section>
      <Section />
      <Section />
    </MainLayout>
  );
};

export default Home;
