import { useEffect, useState } from "react";

import Head from "next/head";

import MainLayout from "../Components/MainLayout";
import Section1 from "../Components/Home/Section1";
import Section2 from "../Components/Home/Section2";
import Section3 from "../Components/Home/Section3";

const Home = () => {
  const [isShown, setIsShown] = useState(false);
  useEffect(() => {
    setIsShown(true);
  }, []);

  if (!isShown) {
    return null;
  }
  return (
    <MainLayout>
      <Head>
        <title>Travel Lamu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section1 />
      <Section2 />
      <Section3 />
    </MainLayout>
  );
};

export default Home;
